# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vector_service.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'vector_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14vector_service.proto\x12\x0bmlxvectordb\"~\n\x06Vector\x12\x0e\n\x06values\x18\x01 \x03(\x02\x12\x33\n\x08metadata\x18\x02 \x03(\x0b\x32!.mlxvectordb.Vector.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\\\n\x11\x41\x64\x64VectorsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12$\n\x07vectors\x18\x03 \x03(\x0b\x32\x13.mlxvectordb.Vector\"E\n\x12\x41\x64\x64VectorsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\x0f\n\x07message\x18\x03 \x01(\t\"g\n\x0cQueryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12)\n\x0cquery_vector\x18\x03 \x01(\x0b\x32\x13.mlxvectordb.Vector\x12\t\n\x01k\x18\x04 \x01(\x05\"\x9e\x01\n\x0fQueryResultItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\x12<\n\x08metadata\x18\x03 \x03(\x0b\x32*.mlxvectordb.QueryResultItem.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"P\n\rQueryResponse\x12-\n\x07results\x18\x01 \x03(\x0b\x32\x1c.mlxvectordb.QueryResultItem\x12\x10\n\x08query_id\x18\x02 \x01(\t\"m\n\x11\x42\x61tchQueryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12*\n\rquery_vectors\x18\x03 \x03(\x0b\x32\x13.mlxvectordb.Vector\x12\t\n\x01k\x18\x04 \x01(\x05\x32\xea\x01\n\rVectorService\x12M\n\nAddVectors\x12\x1e.mlxvectordb.AddVectorsRequest\x1a\x1f.mlxvectordb.AddVectorsResponse\x12>\n\x05Query\x12\x19.mlxvectordb.QueryRequest\x1a\x1a.mlxvectordb.QueryResponse\x12J\n\nBatchQuery\x12\x1e.mlxvectordb.BatchQueryRequest\x1a\x1a.mlxvectordb.QueryResponse0\x01\x42i\n\x13io.mlxvectordb.grpcB\x12VectorServiceProtoP\x01Z<github.com/Theseus-AT/mlx-vector-db/gen/go/grpc_api;grpc_apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023io.mlxvectordb.grpcB\022VectorServiceProtoP\001Z<github.com/Theseus-AT/mlx-vector-db/gen/go/grpc_api;grpc_api'
  _globals['_VECTOR_METADATAENTRY']._loaded_options = None
  _globals['_VECTOR_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_QUERYRESULTITEM_METADATAENTRY']._loaded_options = None
  _globals['_QUERYRESULTITEM_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_VECTOR']._serialized_start=37
  _globals['_VECTOR']._serialized_end=163
  _globals['_VECTOR_METADATAENTRY']._serialized_start=116
  _globals['_VECTOR_METADATAENTRY']._serialized_end=163
  _globals['_ADDVECTORSREQUEST']._serialized_start=165
  _globals['_ADDVECTORSREQUEST']._serialized_end=257
  _globals['_ADDVECTORSRESPONSE']._serialized_start=259
  _globals['_ADDVECTORSRESPONSE']._serialized_end=328
  _globals['_QUERYREQUEST']._serialized_start=330
  _globals['_QUERYREQUEST']._serialized_end=433
  _globals['_QUERYRESULTITEM']._serialized_start=436
  _globals['_QUERYRESULTITEM']._serialized_end=594
  _globals['_QUERYRESULTITEM_METADATAENTRY']._serialized_start=116
  _globals['_QUERYRESULTITEM_METADATAENTRY']._serialized_end=163
  _globals['_QUERYRESPONSE']._serialized_start=596
  _globals['_QUERYRESPONSE']._serialized_end=676
  _globals['_BATCHQUERYREQUEST']._serialized_start=678
  _globals['_BATCHQUERYREQUEST']._serialized_end=787
  _globals['_VECTORSERVICE']._serialized_start=790
  _globals['_VECTORSERVICE']._serialized_end=1024
# @@protoc_insertion_point(module_scope)
