# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vector_service_pb2 as vector__service__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vector_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorServiceStub(object):
    """Der Haupt-Service für Vektoroperationen
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddVectors = channel.unary_unary(
                '/mlxvectordb.VectorService/AddVectors',
                request_serializer=vector__service__pb2.AddVectorsRequest.SerializeToString,
                response_deserializer=vector__service__pb2.AddVectorsResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/mlxvectordb.VectorService/Query',
                request_serializer=vector__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=vector__service__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.BatchQuery = channel.unary_stream(
                '/mlxvectordb.VectorService/BatchQuery',
                request_serializer=vector__service__pb2.BatchQueryRequest.SerializeToString,
                response_deserializer=vector__service__pb2.QueryResponse.FromString,
                _registered_method=True)


class VectorServiceServicer(object):
    """Der Haupt-Service für Vektoroperationen
    """

    def AddVectors(self, request, context):
        """Fügt Vektoren zu einem bestimmten Store hinzu.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Fragt die k nächsten Nachbarn für einen einzelnen Query-Vektor ab.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchQuery(self, request, context):
        """Fragt die k nächsten Nachbarn für mehrere Query-Vektoren im Batch ab.
        Gibt einen Stream von Antworten zurück, eine für jede Query im Request.
        Wie im Plan vorgeschlagen
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.AddVectors,
                    request_deserializer=vector__service__pb2.AddVectorsRequest.FromString,
                    response_serializer=vector__service__pb2.AddVectorsResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=vector__service__pb2.QueryRequest.FromString,
                    response_serializer=vector__service__pb2.QueryResponse.SerializeToString,
            ),
            'BatchQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.BatchQuery,
                    request_deserializer=vector__service__pb2.BatchQueryRequest.FromString,
                    response_serializer=vector__service__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mlxvectordb.VectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mlxvectordb.VectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorService(object):
    """Der Haupt-Service für Vektoroperationen
    """

    @staticmethod
    def AddVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlxvectordb.VectorService/AddVectors',
            vector__service__pb2.AddVectorsRequest.SerializeToString,
            vector__service__pb2.AddVectorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlxvectordb.VectorService/Query',
            vector__service__pb2.QueryRequest.SerializeToString,
            vector__service__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mlxvectordb.VectorService/BatchQuery',
            vector__service__pb2.BatchQueryRequest.SerializeToString,
            vector__service__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
